let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Фонтан (60 см) 3 минуты",
    price: 8,
    desc: "Сценический холодный фонтан. Время действия - 60 секунд. Высота 3 метра.",
    img: "images/cold-fount.jpg",
    videoId: "Sd8xT9kObCI",
  },
  {
    id: "ioytrhndcv",
    name: "Вертушка фонтанов",
    price: 10,
    desc: "Динамически вращающаяся наземная установка с несколькими фонтанами.",
    img: "images/vertushki.jpg",
    videoId: "HoT4A3SnRLE",
  },
  {
    id: "wuefbncxbsn",
    name: "Тяжёлый дым (на улице)",
    price: 300,
    desc: "Время работы: от 3 до 8 минут (зависит от площади и погоды). Дополнительно приобретая запуск в помещении, цена за оба запуска составит 450 руб.",
    img: "images/smoke.jpg",
    videoId: "S395XDsCKDw",
  },
  {
    id: "wudsbafcsbs",
    name: "Тяжёлый дым (в помещении)",
    price: 360,
    desc: "Время работы: от 3 до 8 минут (зависит от площади помещения). Дополнительно приобретая запуск на улице, цена за оба запуска составит 450 руб.",
    img: "images/smoke.jpg",
    videoId: "S395XDsCKDw",
  },
  {
    id: "jopsdfhkjsds",
    name: "Спаркуляры (Искромёты)",
    price: 8,
    desc: "Позволяет регулировать высоту подъёма искр, пожаробезопасность (возможно использовать в залах)",
    img: "images/cold-fount.jpg",
    videoId: "Sd8xT9kObCI",
  },
];
